server:
  port: 5555
  servlet:
    session:
      cookie:
        same-site: "none"
        http-only: true
        secure: true
spring:
  datasource:
    url: jdbc:mysql://192.168.60.131:3306/erp?useUnicode=true&characterEncoding=utf-8
    hikari:
      username: root
      password: 7898
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: info
