server:
  port: 80
  servlet:
    session:
      cookie:
        same-site: strict
        http-only: false
spring:
  datasource:
    url: jdbc:mysql://192.168.60.131:3306/erp?useUnicode=true&characterEncoding=utf-8
    hikari:
      username: root
      password: 7898
      driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: debug
